spring:
  application:
  name: Altus-SpringBoot

  datasource:
    url: jdbc:mysql://localhost:3306/altus_pro
    username: root
    password: password123#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

flyway:
  schemas: altus_pro
  locations: classpath:db/migration

server:
  port: 8081