CREATE TABLE rides
(
    ride_id                     INT PRIMARY KEY AUTO_INCREMENT,
    ride_status                 ENUM ('Scheduled', 'Ongoing', 'Completed', 'Cancelled', 'Rejected') NOT NULL,
    pick_location_id            INT                                                                 NOT NULL,
    drop_off_location_id        INT                                                                 NOT NULL,
    customer_id                 INT                                                                 NOT NULL,
    driver_id                   INT                                                                 NOT NULL,
    ride_date                   DATE                                                                NOT NULL,
    pick_up_time                TIME                                                                NOT NULL,
    drop_off_time               TIME,
    display_id                  VARCHAR(10)                                                         NOT NULL,
    total_km                    DOUBLE                                                              NOT NULL,
    total_cost                  DECIMAL(10, 2)                                                      NOT NULL,
    created_at                  DATETIME                                                            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  DATETIME                                                                     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    payment_mode                ENUM ('Cash', 'Card', 'UPI')                                        NOT NULL,
    payment_status              VARCHAR(10)                                                         NOT NULL,
    commission_percentage       DECIMAL(3, 1)                                                       NOT NULL,
    driver_earning              DECIMAL(10, 2)                                                      NOT NULL,
    system_earning              DECIMAL(10, 2)                                                      NOT NULL,
    cancellation_charge         DECIMAL(10, 2)                                                               DEFAULT 0.00,
    cancellation_driver_earning DECIMAL(10, 2)                                                               DEFAULT 0.00,
    cancellation_system_earning DECIMAL(10, 2)                                                               DEFAULT 0.00,
    driver_penalty              DECIMAL(10, 2)                                                               DEFAULT 0.00,
    FOREIGN KEY (pick_location_id) REFERENCES locations (location_id),
    FOREIGN KEY (drop_off_location_id) REFERENCES locations (location_id),
    FOREIGN KEY (customer_id) REFERENCES users (user_id),
    FOREIGN KEY (driver_id) REFERENCES users (user_id)
);